//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

#![allow(clippy::exhaustive_enums, unused_qualifications)]

use std::fmt::Display;

use crate::{HISTORY_MAX_TRIES, PUZZLE_LETTERS_COUNT, PuzzleDate, PuzzleSolution, SubmitHistory};

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// The `histories` table model.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]
#[sea_orm(table_name = "histories")]
pub struct Model {
    /// The puzzle date.
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: PuzzleDate,
    /// The session token.
    #[sea_orm(primary_key, auto_increment = false)]
    pub session: String,
    /// The submit history in JSON format.
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub submit_history: Option<SubmitHistory>,
    /// The solution submitted.
    pub solution: PuzzleSolution,
    /// Whether the puzzle has been completed.
    pub is_completed: bool,
    /// The timestamp when this history was uploaded.
    pub uploaded_at: DateTime,
}

impl Model {
    /// Returns the number of letters in the puzzle.
    pub fn letters_count(&self) -> usize {
        PUZZLE_LETTERS_COUNT
    }

    /// Returns the number of remaining tries.
    pub fn remaining_tries(&self) -> usize {
        match &self.submit_history {
            Some(submit_history) => submit_history.remaining_tries(),
            None => HISTORY_MAX_TRIES,
        }
    }
}

impl Display for Model {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{:?} -> {} at {} [{}] {{{}}}",
            self.submit_history, self.solution, self.uploaded_at, self.date, self.session
        )
    }
}

/// The relations of the `histories` table.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// The relation to the `puzzles` table.
    #[sea_orm(
        belongs_to = "super::puzzles::Entity",
        from = "Column::Date",
        to = "super::puzzles::Column::Date",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Puzzles,
    /// The relation to the `sessions` table.
    #[sea_orm(
        belongs_to = "super::sessions::Entity",
        from = "Column::Session",
        to = "super::sessions::Column::Session",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Sessions,
}

impl Related<super::puzzles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Puzzles.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
