//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod histories;
pub mod puzzles;
pub mod sessions;

pub const PUZZLE_LETTERS_COUNT: usize = 5;
pub const HISTORY_MAX_TRIES: usize = 6;
