//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

#![allow(clippy::exhaustive_enums, unused_qualifications)]

use crate::{PUZZLE_LETTERS_COUNT, PuzzleDate, PuzzleSolution};

use std::fmt::Display;

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// The `puzzles` table model.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]
#[sea_orm(table_name = "puzzles")]
pub struct Model {
    /// The puzzle date.
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: PuzzleDate,
    /// The puzzle solution.
    pub solution: PuzzleSolution,
}

impl Display for Model {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} [{}]", self.solution, self.date,)
    }
}

impl Model {
    /// Converts this puzzle model into a [`ResultPuzzle`].
    pub fn to_result_puzzle(self) -> ResultPuzzle {
        self.into()
    }
}

/// A puzzle result containing the date and solution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResultPuzzle<const N: usize = PUZZLE_LETTERS_COUNT> {
    /// The puzzle date.
    pub date: PuzzleDate,
    /// The puzzle solution.
    pub solution: PuzzleSolution<N>,
}

impl<const N: usize> Display for ResultPuzzle<N> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} [{}]", self.solution, self.date)
    }
}

impl From<Model> for ResultPuzzle<PUZZLE_LETTERS_COUNT> {
    fn from(Model { date, solution, .. }: Model) -> Self {
        Self { date, solution }
    }
}

/// The relations of the `puzzles` table.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// The relation to the `histories` table.
    #[sea_orm(has_many = "super::histories::Entity")]
    Histories,
}

impl Related<super::histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Histories.def()
    }
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        super::histories::Relation::Sessions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::histories::Relation::Puzzles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
