//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

#![allow(clippy::exhaustive_enums, unused_qualifications)]

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// The `sessions` table model.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    /// The session token.
    #[sea_orm(primary_key, auto_increment = false)]
    pub session: String,
    /// The timestamp when this session was created.
    pub created_at: DateTime,
    /// The timestamp when this session was last updated.
    pub updated_at: DateTime,
}

/// The relations of the `sessions` table.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// The relation to the `histories` table.
    #[sea_orm(has_many = "super::histories::Entity")]
    Histories,
}

impl Related<super::histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Histories.def()
    }
}

impl Related<super::puzzles::Entity> for Entity {
    fn to() -> RelationDef {
        super::histories::Relation::Puzzles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::histories::Relation::Sessions.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
